import {
  Globe, Keyboard, Terminal, Shield, Gamepad2, PlaySquare, Play, Pause,
  SkipForward, SkipBack, Volume2, VolumeX, Music, Code, MessageCircle,
  MessageSquare, Camera, Youtube, Book, User, Github, Monitor, Box, Power,
  LayoutGrid, Image, Video, Radio, Cast, Circle, Square, Mic,
  MicOff, GitBranch, GitPullRequest, AlertCircle, Workflow, Settings2,
  Video as ZoomIcon, Hash, Headphones, Slack as SlackIcon, Users,
  Send, FileText, Chrome, Cpu, Lock, Moon, RefreshCw, Folder,
  Clipboard, Volume1, Search, BellOff, Bell, PhoneCall, PhoneOff,
  Hand, ScreenShare, PlusCircle, ExternalLink, BookOpen, Edit
} from "lucide-react";

export const ACTION_TYPES = [
  // General
  { value: "url" as const,     label: "Open URL",              icon: Globe,        group: "General" },
  { value: "hotkey" as const,  label: "Hotkey / Shortcut",    icon: Keyboard,     group: "General" },
  { value: "script" as const,  label: "Run Script / Command", icon: Terminal,     group: "General" },
  { value: "app" as const,     label: "Launch App",           icon: PlaySquare,   group: "General" },
  { value: "media" as const,   label: "Media Control",        icon: Play,         group: "General" },
  { value: "system" as const,  label: "System",               icon: Cpu,          group: "General" },
  { value: "browser" as const, label: "Browser",              icon: Globe,        group: "General" },
  // Meetings & Chat
  { value: "zoom" as const,    label: "Zoom",                 icon: Video,        group: "Meetings" },
  { value: "teams" as const,   label: "Microsoft Teams",      icon: Users,        group: "Meetings" },
  { value: "discord" as const, label: "Discord",              icon: MessageCircle,group: "Meetings" },
  { value: "slack" as const,   label: "Slack",                icon: Hash,         group: "Meetings" },
  { value: "telegram" as const,label: "Telegram",             icon: Send,         group: "Meetings" },
  // Music & Media
  { value: "spotify" as const, label: "Spotify",              icon: Music,        group: "Music" },
  { value: "obs" as const,     label: "OBS Studio",           icon: Video,        group: "Music" },
  // Dev & Productivity
  { value: "github" as const,  label: "GitHub",               icon: Github,       group: "Dev" },
  { value: "notion" as const,  label: "Notion",               icon: FileText,     group: "Dev" },
  // Gaming
  { value: "steam" as const,   label: "Steam Account",        icon: Gamepad2,     group: "Gaming" },
  { value: "vpn" as const,     label: "Toggle VPN",           icon: Shield,       group: "Other" },
  { value: "twitch" as const,  label: "Twitch",               icon: Cast,         group: "Other" },
];

export type ActionType = typeof ACTION_TYPES[number]["value"];

export const ACTION_VALUE_CONFIG: Record<string, {
  label: string;
  placeholder?: string;
  hint?: string;
  type: "text" | "url" | "select" | "hotkey" | "textarea" | "composite";
  options?: { value: string; label: string }[];
  fields?: { key: string; label: string; placeholder: string; type?: "text" | "url" | "select"; options?: { value: string; label: string }[] }[];
}> = {
  url: {
    label: "URL",
    placeholder: "https://example.com",
    hint: "Full URL to open in the browser",
    type: "url",
  },
  hotkey: {
    label: "Key Combination",
    placeholder: "ctrl+shift+m",
    hint: "Use + to separate keys: ctrl, shift, alt, win, cmd + key",
    type: "hotkey",
  },
  script: {
    label: "Script / Command",
    placeholder: "python script.py  or  notepad.exe",
    hint: "Shell command or script path to execute on the host machine",
    type: "textarea",
  },
  vpn: {
    label: "VPN Action",
    type: "select",
    options: [
      { value: "toggle", label: "Toggle (connect / disconnect)" },
      { value: "connect", label: "Connect" },
      { value: "disconnect", label: "Disconnect" },
    ],
  },
  steam: {
    label: "Steam Account Name",
    placeholder: "MyAccountName",
    hint: "The Steam account login name to switch to",
    type: "text",
  },
  app: {
    label: "Application",
    placeholder: "discord  or  C:\\Program Files\\App\\app.exe",
    hint: "App name or full path to the executable",
    type: "text",
  },
  media: {
    label: "Media Command",
    type: "select",
    options: [
      { value: "playpause", label: "Play / Pause" },
      { value: "nexttrack", label: "Next Track" },
      { value: "prevtrack", label: "Previous Track" },
      { value: "volumeup", label: "Volume Up" },
      { value: "volumedown", label: "Volume Down" },
      { value: "mute", label: "Mute / Unmute" },
      { value: "stop", label: "Stop" },
    ],
  },
  system: {
    label: "System Action",
    type: "select",
    options: [
      { value: "lock", label: "Lock Screen" },
      { value: "sleep", label: "Sleep / Suspend" },
      { value: "shutdown", label: "Shutdown" },
      { value: "restart", label: "Restart" },
      { value: "logoff", label: "Log Off" },
      { value: "screenshot", label: "Screenshot" },
      { value: "screenrecord", label: "Start / Stop Screen Recording" },
      { value: "taskmanager", label: "Open Task Manager" },
      { value: "explorer", label: "Open File Explorer" },
      { value: "clipboard", label: "Open Clipboard History (Win+V)" },
      { value: "emoji", label: "Open Emoji Picker (Win+.)" },
      { value: "desktop", label: "Show Desktop" },
      { value: "notification", label: "Open Notification Center" },
    ],
  },
  browser: {
    label: "Browser Action",
    type: "select",
    options: [
      { value: "newtab", label: "New Tab" },
      { value: "newwindow", label: "New Window" },
      { value: "incognito", label: "New Incognito Window" },
      { value: "bookmark", label: "Bookmark Current Page" },
      { value: "history", label: "Open History" },
      { value: "downloads", label: "Open Downloads" },
      { value: "devtools", label: "Toggle DevTools" },
      { value: "hardrefresh", label: "Hard Refresh (Ctrl+Shift+R)" },
      { value: "fullscreen", label: "Toggle Fullscreen" },
      { value: "zoomin", label: "Zoom In" },
      { value: "zoomout", label: "Zoom Out" },
      { value: "zoomreset", label: "Reset Zoom" },
    ],
  },
  zoom: {
    label: "Zoom Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Command",
        type: "select",
        placeholder: "Select Zoom action",
        options: [
          { value: "mute", label: "Mute / Unmute Microphone" },
          { value: "video", label: "Start / Stop Video" },
          { value: "screenshare", label: "Start / Stop Screen Share" },
          { value: "hand", label: "Raise / Lower Hand" },
          { value: "record", label: "Start / Stop Recording" },
          { value: "leave", label: "Leave Meeting" },
          { value: "end", label: "End Meeting (host)" },
          { value: "chat", label: "Open Chat" },
          { value: "participants", label: "Show Participants" },
          { value: "reactions", label: "Send Reaction" },
          { value: "newmeeting", label: "Start New Meeting" },
          { value: "join", label: "Join Meeting" },
          { value: "schedule", label: "Schedule Meeting" },
        ],
      },
      {
        key: "meetingId",
        label: "Meeting ID or Link (for Join)",
        type: "text",
        placeholder: "https://zoom.us/j/... or 123-456-789",
      },
    ],
  },
  teams: {
    label: "Microsoft Teams Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Command",
        type: "select",
        placeholder: "Select Teams action",
        options: [
          { value: "mute", label: "Mute / Unmute Microphone" },
          { value: "video", label: "Start / Stop Camera" },
          { value: "screenshare", label: "Share Screen" },
          { value: "hand", label: "Raise Hand" },
          { value: "leave", label: "Leave Call" },
          { value: "chat", label: "Open Chat" },
          { value: "calendar", label: "Open Calendar" },
          { value: "teams-tab", label: "Open Teams Tab" },
          { value: "newcall", label: "Start New Call" },
          { value: "blur", label: "Toggle Background Blur" },
          { value: "reactions", label: "Send Reaction" },
        ],
      },
      {
        key: "contact",
        label: "Contact / Channel (for Call/Chat)",
        type: "text",
        placeholder: "John Doe or #general",
      },
    ],
  },
  discord: {
    label: "Discord Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Command",
        type: "select",
        placeholder: "Select Discord action",
        options: [
          { value: "mute", label: "Mute / Unmute Microphone" },
          { value: "deafen", label: "Deafen / Undeafen" },
          { value: "video", label: "Toggle Video" },
          { value: "screenshare", label: "Start / Stop Screen Share" },
          { value: "disconnect", label: "Disconnect from Voice" },
          { value: "push-to-talk", label: "Push to Talk" },
          { value: "open-channel", label: "Open Channel" },
          { value: "open-dm", label: "Open Direct Message" },
          { value: "go-live", label: "Go Live / Stream" },
          { value: "notifications-off", label: "Suppress Notifications" },
          { value: "invite", label: "Create Invite" },
        ],
      },
      {
        key: "target",
        label: "Channel / User (for Open actions)",
        type: "text",
        placeholder: "#general  or  @username",
      },
    ],
  },
  slack: {
    label: "Slack Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Command",
        type: "select",
        placeholder: "Select Slack action",
        options: [
          { value: "open", label: "Open Slack" },
          { value: "new-message", label: "New Message" },
          { value: "open-channel", label: "Open Channel" },
          { value: "set-status", label: "Set Status" },
          { value: "dnd", label: "Toggle Do Not Disturb" },
          { value: "mute-notifs", label: "Mute Notifications" },
          { value: "open-huddle", label: "Start Huddle" },
          { value: "open-dm", label: "Open Direct Message" },
          { value: "search", label: "Open Search" },
          { value: "open-threads", label: "Open Threads" },
          { value: "open-mentions", label: "Open Mentions & Reactions" },
        ],
      },
      {
        key: "target",
        label: "Channel / User / Status text",
        type: "text",
        placeholder: "#general  or  @john  or  In a meeting",
      },
    ],
  },
  spotify: {
    label: "Spotify Action",
    type: "select",
    options: [
      { value: "playpause", label: "Play / Pause" },
      { value: "next", label: "Next Track" },
      { value: "prev", label: "Previous Track" },
      { value: "volumeup", label: "Volume Up" },
      { value: "volumedown", label: "Volume Down" },
      { value: "mute", label: "Mute / Unmute" },
      { value: "shuffle", label: "Toggle Shuffle" },
      { value: "repeat", label: "Toggle Repeat" },
      { value: "like", label: "Like / Save Current Song" },
      { value: "open", label: "Open Spotify" },
      { value: "open-liked", label: "Open Liked Songs" },
      { value: "open-queue", label: "Open Queue" },
    ],
  },
  telegram: {
    label: "Telegram Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Command",
        type: "select",
        placeholder: "Select Telegram action",
        options: [
          { value: "open", label: "Open Telegram" },
          { value: "open-chat", label: "Open Chat" },
          { value: "new-message", label: "New Message" },
          { value: "saved", label: "Open Saved Messages" },
          { value: "calls", label: "Open Calls" },
        ],
      },
      {
        key: "target",
        label: "Username or Chat",
        type: "text",
        placeholder: "@username  or  +7 999 123 45 67",
      },
    ],
  },
  notion: {
    label: "Notion Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Command",
        type: "select",
        placeholder: "Select Notion action",
        options: [
          { value: "open", label: "Open Notion" },
          { value: "new-page", label: "Create New Page" },
          { value: "open-page", label: "Open Page" },
          { value: "search", label: "Quick Search" },
          { value: "inbox", label: "Open Inbox" },
          { value: "templates", label: "Open Templates" },
        ],
      },
      {
        key: "pageUrl",
        label: "Page URL or ID (for Open Page)",
        type: "text",
        placeholder: "https://notion.so/My-Page-abc123...",
      },
    ],
  },
  obs: {
    label: "OBS Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Command",
        type: "select",
        placeholder: "Select OBS command",
        options: [
          { value: "start-recording", label: "Start Recording" },
          { value: "stop-recording", label: "Stop Recording" },
          { value: "toggle-recording", label: "Toggle Recording" },
          { value: "start-streaming", label: "Start Streaming" },
          { value: "stop-streaming", label: "Stop Streaming" },
          { value: "toggle-streaming", label: "Toggle Streaming" },
          { value: "switch-scene", label: "Switch Scene" },
          { value: "toggle-mute-mic", label: "Toggle Mute Microphone" },
          { value: "toggle-mute-desktop", label: "Toggle Mute Desktop Audio" },
          { value: "screenshot", label: "Save Screenshot" },
          { value: "replay-buffer", label: "Toggle Replay Buffer" },
          { value: "save-replay", label: "Save Replay Buffer" },
        ],
      },
      {
        key: "scene",
        label: "Scene Name (for Switch Scene)",
        type: "text",
        placeholder: "Gaming  or  Just Chatting",
      },
    ],
  },
  github: {
    label: "GitHub Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Action",
        type: "select",
        placeholder: "Select GitHub action",
        options: [
          { value: "open-repo", label: "Open Repository" },
          { value: "open-prs", label: "Open Pull Requests" },
          { value: "open-issues", label: "Open Issues" },
          { value: "open-actions", label: "Open Actions (CI/CD)" },
          { value: "open-commits", label: "Open Commits" },
          { value: "new-issue", label: "Create New Issue" },
          { value: "new-pr", label: "Create New PR" },
          { value: "open-profile", label: "Open My Profile" },
          { value: "open-notifications", label: "Open Notifications" },
          { value: "open-explore", label: "Open Explore" },
          { value: "open-copilot", label: "Open GitHub Copilot Chat" },
        ],
      },
      {
        key: "repo",
        label: "Repository (owner/repo or URL)",
        type: "text",
        placeholder: "octocat/Hello-World",
      },
    ],
  },
  twitch: {
    label: "Twitch Action",
    type: "composite",
    fields: [
      {
        key: "command",
        label: "Action",
        type: "select",
        placeholder: "Select Twitch action",
        options: [
          { value: "open-channel", label: "Open Channel" },
          { value: "open-dashboard", label: "Open Creator Dashboard" },
          { value: "open-analytics", label: "Open Analytics" },
          { value: "open-chat", label: "Open Chat" },
          { value: "open-stream-manager", label: "Open Stream Manager" },
          { value: "clip", label: "Open Clips" },
          { value: "schedule", label: "Open Schedule" },
          { value: "open-homepage", label: "Open Twitch Homepage" },
        ],
      },
      {
        key: "channel",
        label: "Channel Name",
        type: "text",
        placeholder: "xqc  or  ninja",
      },
    ],
  },
};

export const BUTTON_COLORS = [
  { id: "teal", label: "Teal", class: "bg-teal-500", hex: "#14b8a6" },
  { id: "purple", label: "Purple", class: "bg-purple-500", hex: "#a855f7" },
  { id: "orange", label: "Orange", class: "bg-orange-500", hex: "#f97316" },
  { id: "red", label: "Red", class: "bg-red-500", hex: "#ef4444" },
  { id: "green", label: "Green", class: "bg-green-500", hex: "#22c55e" },
  { id: "blue", label: "Blue", class: "bg-blue-500", hex: "#3b82f6" },
  { id: "pink", label: "Pink", class: "bg-pink-500", hex: "#ec4899" },
  { id: "yellow", label: "Yellow", class: "bg-yellow-500", hex: "#eab308" },
  { id: "slate", label: "Slate", class: "bg-slate-700", hex: "#334155" },
];

export const ICONS = [
  { name: "Globe", icon: Globe },
  { name: "Keyboard", icon: Keyboard },
  { name: "Terminal", icon: Terminal },
  { name: "Shield", icon: Shield },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "PlaySquare", icon: PlaySquare },
  { name: "Play", icon: Play },
  { name: "Pause", icon: Pause },
  { name: "SkipForward", icon: SkipForward },
  { name: "SkipBack", icon: SkipBack },
  { name: "Volume2", icon: Volume2 },
  { name: "VolumeX", icon: VolumeX },
  { name: "Volume1", icon: Volume1 },
  { name: "Music", icon: Music },
  { name: "Code", icon: Code },
  { name: "MessageCircle", icon: MessageCircle },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "Camera", icon: Camera },
  { name: "Youtube", icon: Youtube },
  { name: "Book", icon: Book },
  { name: "User", icon: User },
  { name: "Users", icon: Users },
  { name: "Github", icon: Github },
  { name: "Monitor", icon: Monitor },
  { name: "Box", icon: Box },
  { name: "Power", icon: Power },
  { name: "LayoutGrid", icon: LayoutGrid },
  { name: "Image", icon: Image },
  { name: "Video", icon: Video },
  { name: "Radio", icon: Radio },
  { name: "Cast", icon: Cast },
  { name: "Circle", icon: Circle },
  { name: "Square", icon: Square },
  { name: "Mic", icon: Mic },
  { name: "MicOff", icon: MicOff },
  { name: "GitBranch", icon: GitBranch },
  { name: "GitPullRequest", icon: GitPullRequest },
  { name: "AlertCircle", icon: AlertCircle },
  { name: "Workflow", icon: Workflow },
  { name: "Settings2", icon: Settings2 },
  { name: "Hash", icon: Hash },
  { name: "Headphones", icon: Headphones },
  { name: "Send", icon: Send },
  { name: "FileText", icon: FileText },
  { name: "Chrome", icon: Chrome },
  { name: "Cpu", icon: Cpu },
  { name: "Lock", icon: Lock },
  { name: "Moon", icon: Moon },
  { name: "RefreshCw", icon: RefreshCw },
  { name: "Folder", icon: Folder },
  { name: "Clipboard", icon: Clipboard },
  { name: "Search", icon: Search },
  { name: "BellOff", icon: BellOff },
  { name: "Bell", icon: Bell },
  { name: "PhoneCall", icon: PhoneCall },
  { name: "PhoneOff", icon: PhoneOff },
  { name: "Hand", icon: Hand },
  { name: "ScreenShare", icon: ScreenShare },
  { name: "PlusCircle", icon: PlusCircle },
  { name: "ExternalLink", icon: ExternalLink },
  { name: "BookOpen", icon: BookOpen },
  { name: "Edit", icon: Edit },
];

export function serializeCompositeValue(fields: Record<string, string>): string {
  return JSON.stringify(fields);
}

export function parseCompositeValue(raw: string): Record<string, string> {
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === "object" && parsed !== null) return parsed as Record<string, string>;
  } catch {
  }
  return {};
}
